services:
    db:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: U3BvcnRTcGhlcmUK
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - sportssphere-network

    app:
        build: .
        environment:
            MONGO_URL: "mongodb://root:U3BvcnRTcGhlcmUK@db:27017" # for credentials purpose , can be moved to .env file later. @nibrasmuhamed
        depends_on:
        - db
        networks:
        - sportssphere-network
        ports:
            - "8000:8000"

volumes:
    mongo-data:

networks:
    sportssphere-network:
        driver: bridge
